<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SeaBattle.Domain\SeaBattle.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="7.0.16" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.SignalR.Core">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\7.0.13\Microsoft.AspNetCore.SignalR.Core.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
