// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeaBattle.Persistence;

#nullable disable

namespace SeaBattle.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241023210148_SeedDataForShipAndCoordinateTypes")]
    partial class SeedDataForShipAndCoordinateTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeaBattle.Domain.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("AppUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.BaseShip", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShipId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipId"));

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("Direction");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Range")
                        .HasColumnType("int")
                        .HasColumnName("Range");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ShipTypeId");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("Size");

                    b.Property<int>("Speed")
                        .HasColumnType("int")
                        .HasColumnName("Speed");

                    b.HasKey("ShipId");

                    b.HasIndex("ShipTypeId");

                    b.ToTable("Ships");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseShip");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Coordinate", b =>
                {
                    b.Property<int>("CoordinateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CoordinateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoordinateId"));

                    b.Property<int>("CoordinateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CoordinateTypeId");

                    b.Property<int>("GameFieldId")
                        .HasColumnType("int")
                        .HasColumnName("GameFieldId");

                    b.Property<bool>("IsFirstCoordinate")
                        .HasColumnType("bit")
                        .HasColumnName("IsFirstCoordinate");

                    b.Property<int>("PointId")
                        .HasColumnType("int")
                        .HasColumnName("PointId");

                    b.Property<int>("Quadrant")
                        .HasColumnType("int")
                        .HasColumnName("Quadrant");

                    b.HasKey("CoordinateId");

                    b.HasIndex("CoordinateTypeId");

                    b.HasIndex("GameFieldId");

                    b.HasIndex("PointId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.CoordinateType", b =>
                {
                    b.Property<int>("CoordinateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CoordinateTypeId");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("CoordinateTypeId");

                    b.ToTable("CoordinateTypes");

                    b.HasData(
                        new
                        {
                            CoordinateTypeId = 1,
                            Type = "Empty"
                        },
                        new
                        {
                            CoordinateTypeId = 2,
                            Type = "Filled"
                        },
                        new
                        {
                            CoordinateTypeId = 3,
                            Type = "Hit"
                        },
                        new
                        {
                            CoordinateTypeId = 4,
                            Type = "Missed"
                        },
                        new
                        {
                            CoordinateTypeId = 5,
                            Type = "Destroyed"
                        });
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GameId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("Progress");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.GameField", b =>
                {
                    b.Property<int>("GameFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GameFieldId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameFieldId"));

                    b.Property<int>("BoundaryCoordinate")
                        .HasColumnType("int")
                        .HasColumnName("BoundaryCoordinate");

                    b.Property<int>("FieldSize")
                        .HasColumnType("int")
                        .HasColumnName("FieldSize");

                    b.HasKey("GameFieldId");

                    b.ToTable("GameFields");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.GameInvitation", b =>
                {
                    b.Property<int>("GameInvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GameInvitationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameInvitationId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int")
                        .HasColumnName("AppUserId");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameId");

                    b.HasKey("GameInvitationId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GameId");

                    b.ToTable("GameInvitations");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Point", b =>
                {
                    b.Property<int>("PointId")
                        .HasColumnType("int")
                        .HasColumnName("PointId");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("PointId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.ShipCoordinate", b =>
                {
                    b.Property<int>("ShipCoordinateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShipCoordinateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipCoordinateId"));

                    b.Property<int>("CoordinateId")
                        .HasColumnType("int")
                        .HasColumnName("CoordinateId");

                    b.Property<int>("ShipId")
                        .HasColumnType("int")
                        .HasColumnName("ShipId");

                    b.HasKey("ShipCoordinateId");

                    b.HasIndex("CoordinateId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipCoordinates");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.ShipType", b =>
                {
                    b.Property<int>("ShipTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ShipTypeId");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasKey("ShipTypeId");

                    b.ToTable("ShipTypes");

                    b.HasData(
                        new
                        {
                            ShipTypeId = 1,
                            Type = "War"
                        },
                        new
                        {
                            ShipTypeId = 2,
                            Type = "Support"
                        },
                        new
                        {
                            ShipTypeId = 3,
                            Type = "Hybrid"
                        });
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.UserGames", b =>
                {
                    b.Property<int>("UserGamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserGamesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGamesId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int")
                        .HasColumnName("AppUserId");

                    b.Property<int>("GameFieldId")
                        .HasColumnType("int")
                        .HasColumnName("GameFieldId");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("GameId");

                    b.Property<bool>("IsPlayerTurn")
                        .HasColumnType("bit")
                        .HasColumnName("IsPlayerTurn");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit")
                        .HasColumnName("IsReady");

                    b.HasKey("UserGamesId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("GameFieldId");

                    b.HasIndex("GameId");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.HybridShip", b =>
                {
                    b.HasBaseType("SeaBattle.Domain.Models.BaseShip");

                    b.ToTable("Ships");

                    b.HasDiscriminator().HasValue("HybridShip");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.SupportShip", b =>
                {
                    b.HasBaseType("SeaBattle.Domain.Models.BaseShip");

                    b.ToTable("Ships");

                    b.HasDiscriminator().HasValue("SupportShip");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.WarShip", b =>
                {
                    b.HasBaseType("SeaBattle.Domain.Models.BaseShip");

                    b.ToTable("Ships");

                    b.HasDiscriminator().HasValue("WarShip");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.BaseShip", b =>
                {
                    b.HasOne("SeaBattle.Domain.Models.ShipType", "ShipType")
                        .WithMany()
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipType");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Coordinate", b =>
                {
                    b.HasOne("SeaBattle.Domain.Models.CoordinateType", "CoordinateType")
                        .WithMany()
                        .HasForeignKey("CoordinateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.GameField", "GameField")
                        .WithMany("Coordinates")
                        .HasForeignKey("GameFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoordinateType");

                    b.Navigation("GameField");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.GameInvitation", b =>
                {
                    b.HasOne("SeaBattle.Domain.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.Game", "Game")
                        .WithMany("GameInvitations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.ShipCoordinate", b =>
                {
                    b.HasOne("SeaBattle.Domain.Models.Coordinate", "Coordinate")
                        .WithMany("ShipCoordinates")
                        .HasForeignKey("CoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.BaseShip", "Ship")
                        .WithMany("ShipCoordinates")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinate");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.UserGames", b =>
                {
                    b.HasOne("SeaBattle.Domain.Models.AppUser", "AppUser")
                        .WithMany("UserGames")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.GameField", "GameField")
                        .WithMany()
                        .HasForeignKey("GameFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaBattle.Domain.Models.Game", "Game")
                        .WithMany("GameUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Game");

                    b.Navigation("GameField");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.AppUser", b =>
                {
                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.BaseShip", b =>
                {
                    b.Navigation("ShipCoordinates");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Coordinate", b =>
                {
                    b.Navigation("ShipCoordinates");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.Game", b =>
                {
                    b.Navigation("GameInvitations");

                    b.Navigation("GameUsers");
                });

            modelBuilder.Entity("SeaBattle.Domain.Models.GameField", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
