CREATE LOGIN MyLogin WITH PASSWORD = 'SuperPassword.123456789';

CREATE USER Manager FOR LOGIN MyLogin;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.Coordinates TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.CoordinateTypes TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.GameFields TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.Points TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.ShipCoordinates TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.Ships TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON dbo.ShipTypes TO Manager;


SELECT * FROM SeaBattleDb.sys.database_principals;

SELECT * FROM fn_my_permissions('dbo.Coordinates', 'OBJECT');